# Site settings
title: Migaja Pastelería
description: Pastelería Migaja Bolivia
keywords: Modern, Blogging, Fun
author: Liz Viscarra
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://migaja-bolivia.github.io/" # the base hostname & protocol for your site
